export const modern = [
    "Teko",
    "Michroma",
    "Baumans",
    "Expletus Sans",
    "Kanit",
    "Jura",
    "Maven Pro",
    "Allan",
    "Tinos",
    "Economica",
    "Abel",
    "Cabin Condensed",
    "Assistant",
    "Open Sans",
    "Roboto Condensed",
]

export const futuristic = [
    "Wire One",
    "Syncopate",
    "Josefin Slab",
    "Advent Pro", 
    "Orbitron",
    "Rajdhani",
    "Exo 2.0",
    "Audiowide",
    "Expletus Sans ",
    "Quantico",
    "Iceland",
    "Electrolize",
    "Monofett",
    "Sarpanch",
    "Share Tech Mono",
]

  
export const handWritten= [
    "Alex Brush",
    "Great Vibes",
    "Sacramento",
    "Monsieur La Doulaise",
    "Ruthie",
    "Qwigley",
    "Mr Dafoe",
    "Montez",
    "Amatic SC",
    "Princess Sofia",
    "Herr Von Muellerhoff",
    "Stalemate",
    "Mountains of Christmas",
    "Butterfly Kids",
    "Meddon",
]


export const rounded = [
    "Quicksand",
    "Nunito",
    "Dosis",
    "Comfortaa",
    "Fredoka",
    "Shrikhand",
    "Shadows Into Light Two",
    "Happy Monkey",
    "Allan",
    "Text Me One",
    "SirinStencil",
    "Flamenco",
    "Corben",
    "Macondo Swash Caps",
    "Snigle",
]

export const retro = [
    "Monoton",
    "Sacramento",
    "Parisienne",
    "Cookie",
    "Mouse Memoirs",
    "Lobster",
    "Yellowtai",
    "Oregano",
    "Bubblegum Sans",
    "Chicle",
    "Righteous",
    "Emilys Candy",
    "Boogaloo",
    "Cherry Cream Soda",
    "Englebert",
]

export const light = [
    "Open Sans",
    "Roboto",
    "Raleway",
    "Source Sans Pro",
    "Oswald",
    "Cinzel",
    "Exo",
    "Lato",
    "Josefin Sans",
    "Advent Pro",
    "Alegreya Sans SC",
    "Barlow",
    "Life Savers",
    "Kalam",
    "Text Me One",
]

export default {modern,futuristic,handWritten,rounded,retro,light}